version: '2'

services:
  app:
    image: 'accepted-assessment:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=accepted
      - SPRING_DATASOURCE_PASSWORD=accepted
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"   
       
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=accepted
      - POSTGRES_PASSWORD=accepted
    ports:
      - "5432:5432"

  pgadmin:
    container_name: db_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: accepted@accepted.com
      PGADMIN_DEFAULT_PASSWORD: accepted
    ports:
      - "5050:80"